robobo_container:
  ros__parameters:
    robot_name: "0"
    ip: localhost
    robot_id: 0

    modules:
      - imu
      - brightness
      - speech
      - audio
      - noise
      - emotion
      - camera
      - qr
      - aruco
      - blob
      - object_recognition
      - touch

